baseURL = 'https://www.rohanhussain.com/blog'
languageCode = 'en-us'
title = "Rohan Hussain's Blog"
theme = "ananke"
summaryLength = 20
disqusShortname = "rohanhussain-com-blog"
googleAnalytics = "G-G62YG0ET9R"

[params]
    navbarLinkTitle = "Blog Home"

[menus]
    main = [{name = "All Posts", url='/posts'}, {name = 'Portfolio Home', url = 'https://rohanhussain.com'}]